# INSTRUCTIONS: Copy this entire file content
# Paste it into: .github/workflows/build-oscar.yml on GitHub

name: Build OSCAR EMR Docker Image

on:
  push:
    branches:
      - claude/oscaremr-docker-selfhost-011CUy5PmCJy4pvghnoX1eRX
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/oscar-emr
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push OSCAR EMR image
        uses: docker/build-push-action@v5
        with:
          context: deployment
          file: deployment/oscar/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push other services
        run: |
          cd deployment

          # Build integrations service
          docker build -t ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/integrations:latest ./integrations
          docker push ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/integrations:latest

          # Build backup service
          docker build -t ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/backup:latest ./backup
          docker push ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/backup:latest

          # Build setup-wizard
          docker build -t ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/setup-wizard:latest ./setup-wizard
          docker push ghcr.io/${{ github.repository_owner }}/clinistream-oscaremr/setup-wizard:latest
