name: Update drug data

on:
  schedule:
    - cron: '0 3 * * *'   # every day at 3 AM UTC
  workflow_dispatch:     # also allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch & compile drug data
        run: python build_compiled_data.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add compiled_drug_data.json
          git commit -m "Auto‑update compiled_drug_data.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
