name: Update Drug Data

on:
  schedule:
    - cron: '0 3 * * *'   # Run every day at 3 AM UTC
  workflow_dispatch:       # Allow manual workflow runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Debugging - Show Python environment
      - name: Debug Python environment
        run: |
          python --version
          pip --version
          echo "Current working directory: $(pwd)"
          echo "List of files in directory:"
          ls -R

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: pip install requests

      # Step 5: Run the Python script
      - name: Run drug data compilation script
        run: |
          echo "Starting build_compiled_drug_data.py script..."
          python build_compiled_drug_data.py
        env:
          DEBUG: "true"  # Pass a debug variable to the script

      # Step 6: Debugging - Check for output files
      - name: Debug output files
        run: |
          echo "Checking output files..."
          ls -lh
          echo "Contents of compiled_drug_data.json:"
          head -n 20 compiled_drug_data.json || echo "File not found!"
          echo "Checking compressed JSON (.gz):"
          ls -lh compiled_drug_data.json.gz || echo "Compressed file not found!"

      # Step 7: Commit and push updated JSON files
      - name: Commit updated JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add compiled_drug_data.json compiled_drug_data.json.gz
          git commit -m "Auto-update compiled_drug_data.json and compiled_drug_data.json.gz"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
